### ISSUE TITLE
MIUI12 一直常驻一个通知，有什么办法关闭吗

### ISSUE THREAD

**Issue by Kelcoin** [Vove7/EnergyRing#1]
![Screenshot_2020-11-14-13-09-41-933_com miui home](https://user-images.githubusercontent.com/10922375/99140223-cf41e580-267a-11eb-90b8-385f0b1ba8e3.jpg)

**Comment by Vove7** [comment]
一般是能进通知管理关掉，如果miui没阉割的话

**Comment by Kelcoin** [comment]
多谢，解决了
